### PR TITLE
Use Travis to deploy to docker hub

### LINKED ISSUE #31: Automated builds are nice, but we have travis too
docker hub is doing auto builds, which is nice.

but travis is building the images for testing anyway and we can inject some other label schema parameters in travis.

We should use the build images in travis and docker push them to docker-hub when built.

- [ ] add docker login encrypted fields for use in travis
- [ ] add commit version into docker image using `ARG`'s
- [ ] add `make push` command to send stuff to docker hub

### PR DESCRIPTION
**Pull request by h-bragg**
Resolves #31 

- Use docker login to deploy to dockerhub
- Add proper labels to each image
- Add build date and commit hash to each image
- Add tests for labels
- Parallel builds in travis

**N.B.** this uses `sudo` to remove test files after each test (bad, but travis runs docker through sudo it seems)

### CODE REVIEW

**Comment by h-bragg** [comment]
@biggianteye mind having a look?

**Comment by biggianteye** [comment]
Is there an example of this in action that I could have a look at?

**Comment by h-bragg** [comment]
https://github.com/graze/docker-php-alpine
https://travis-ci.org/graze/docker-php-alpine

**Review by biggianteye — APPROVED** [review]
The sudo thing is a little unfortunate, but other than that this looks fine. Will be interesting to see it in action.

**Comment by biggianteye** [comment]
Do you intend to remove the autobuild on dockerhub?

**Comment by h-bragg** [comment]
This doesn't autobuild currently, the old travis calls the build trigger, so no changes required.

**Pull request merged**
