### PR TITLE
Fix cache permissions

### PR DESCRIPTION
**Pull request by sjparkinson**
After moving to running under a `composer` user the cache directory permissions got messed up:

screen shot 2016-04-04 at 12 32 53 pm

Removing the volumes in the image is the fix, as they otherwise get mounted as root.

I also took the time to remove some layers and give the user a group too.

### CODE REVIEW

**Comment by biggianteye** [comment]
There are still permission problems when trying to use the container as the composer user does not have  permission to modify files on the host file system using the volume mapping `~/.composer:/home/composer/.composer`

image

**Comment by sjparkinson** [comment]
So I'm not sure how you were testing, but I've added some tests, that fail on `master` due to the volume statments, but pass on this branch.

Any steps I could follow to reproduce it?

**Comment by sjparkinson** [comment]
#23 needs to be merged btw too, some changes to composer mean the image is currently missing a PHP extension.

**Comment by biggianteye** [comment]
I've merged #23 so this i now conflicted. Once that's sorted out I'll test it again and we can talk about any failures.

**Comment by sjparkinson** [comment]
:boom: finally got tests to pass. I've had to revert back to the root user though, volumes and non-root really don't seem compatiable.

**Comment by biggianteye** [comment]
`make test` now prompts for a password for `sudo`. Giving root access to a test make me uncomfortable. Is there an alternative way to deal with cleanup?

**Comment by sjparkinson** [comment]
Doesn't actually seem to be required locally, but does on Travis, odd differences in the volume mounting setup I suppose. I've removed it and added `sudo` before the `make test` in travis.yml.

Of note, this also fixes the wget ssl errors that started recently.

**Pull request merged**
